export const dictimArr = [
    "Trường học cỏ khả năng hô biến người thắng và người bại, nhưng cuộc sống thì không",
    "Nhà trường cho ta chiếc chìa khóa của tri thức, học tập trong cuộc sống chính là công việc cả đời",
    "Giáo dục là vũ khí mạnh nhất nó có thể thay đổi cả thế giới này",
    "Đừng xấu hổ khi bạn không biết, ta chỉ xấu hổ khi không học",
    "Học tập đơn giản là hạt giống của kiến thức, kiến thức là hạt giống của hạnh phúc",
    "Những gì chúng ta biết trong ngày hôm nay ngày hôm sau sẽ lỗi thời. Nếu ngừng học tập thì chúng ta sẽ ngừng phát triển",
    "Không có giới hạn qui trình học, cách học. Khi con người có được húng thú để tìm những con đường mới để kết cấu nên tri thức, họ sẽ không sợ bị buồn chán",
    "Người thầy trong học vấn giống như một ngọn lửa. Nếu tới quá gần sẽ bị thiêu cháy. Nếu bạn quá xa sẽ không thấy đủ ấm. Bạn nên tiếp cận một cách vừa phải",
    "Hãy nên nhớ rằng : học tập thực sự hiệu quả khi nó thực sự vui thích",
    "Hãy học khi người khác ngủ, lao động khi người khác lười nhác, chuẩn bị khi người khác chơi bời và có được giấc mơ của mình khi mọi người chỉ ao ước",
    "Sự ngu dốt không đáng xấu hổ bằng việc không chịu học hỏi",
    "Người học trò luôn bắt đầu bằng cách tìm ra khiếm khuyết, còn nhà học giả thấy ưu điểm trong mọi thứ",
    "Học tập là khả năng tìm ra ý nghĩa của một điều gì đó bạn quan sát dựa trên những trải nghiệm trong quá khứ và nhận xét rồi liên kết quan sát đấy với ý nghĩa của nó",
    "Biết cách học là đủ chứng tỏ bạn thông thái",
    "Thiên tài cũng không là gì khác ngoài sự kiên trì và nhẫn nại",
    "Vũ trụ có biết bao nhiêu điều kì thú chờ đợi ta ở phía trước",
    "Phải luôn luôn học tập chừng nào còn một đều chưa biết",
    "Không có kho báu nào quý bằng học thức. Hãy tích lũy nó bất cứ lúc nào có thể",
    "Điều chúng ta biết chỉ là một giọt nước. Điều chúng ta không biết mênh mông như đại dương",
    "Học tập có thể định nghĩa như là quá trình ghi nhớ những điều bạn thích",
    "Đối với người trưởng thành, sự lựa chọn đầu tiên là luôn xem xét và tự quản lý việc học tập",
    "Những gì chúng ta biết ngày hôm nay sẽ lỗi thời vào ngày hôm sau. Nếu chúng ta ngừng học thì chúng ta sẽ ngừng phát triển",
    "Hãy khắc ghi những từ này vào trong đầu bạn : học tập sẽ hiệu quả hơn khi nó thực sự vui thích",
    "Đối với tôi học tập có nghĩa là sự tò mò không giới hạn bất cứ chủ đề nào và không bao giờ chấp nhận câu trả lời cuối cùng cho đến khi chúng ta đã khám phá mọi khả năng có thể và không còn gì hơn nữa để biết",
    "Người nào ngừng học tập đều trở nên già cả, dù ở tuổi 20 hay 80. Bất cứ ai liên tục học tập đều trẻ trung. Điều vĩ đại nhất trong cuộc sống là giữ cho trí não của bạn tươi trẻ",
    "Học tập không phải là một nhiệm vụ hay một vấn đề khó giải quyết – nó là cách để sống trong thế giới. Con người học tập khi theo đuổi các mục tiêu và kế hoạch có ý nghĩa cho chính mình",
    "Học tập là điều cốt lõi của sự khiêm nhường – học từ vạn vật và từ mọi người. Không có tôn ti thứ bậc trong học tập. Người có quyền hành chối bỏ học hành và người tuân theo cũng thế",
    "Không có giới hạn cho qui trình học, cách để học. Thực sự một khi con người đã có được húng thú để tìm những con đường mới để kết cấu nên tri thức, họ sẽ không bao giờ sợ bị buồn chán",
    "Không có giới hạn cho quy trình học cách để học. Sự thực một khi con người đã có được hứng thú để tìm những con đường mới để kết cấu nên tri thức, họ sẽ không bao giờ sợ bị buồn chán",
    "The most beautiful thing about learning is that no one take that away form you",
    "Study not what the world is doing, but what you can do for it",
    "Adventure is the best way to learn",
    "Once you stop learning, you’ll start dying",
    "Study the past if you would define the future",
    "Learning is the eye of the mind",
    "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you",
    "Learning is the treasure that will follow its owner everywhere",
    "Education is the most powerful weapon we use to change the world",
    "Live as if you were to die tomorrow, learn as if you were to live forever",
    "The adventure of life is to learn. The purpose of life is to grow. The nature of life is to change. The challenge of life is to overcome. The essence of life is to care. The opportunity of like is to serve. The secret of life is to dare. The spice of life is to befriend. The beauty of life is to give",
    "Study while others are sleeping, work while others are loafing, prepare while others are playing, and dream while others are wishing"
];
